replicaCount: 1

image:
  repository: "javierumunir/portal-tfe"
  tag: "d77635322d8406f303a19b71dbdfc2b06a644819"

service:
  type: ClusterIP
  port: 80

ingress:
  className: nginx
  hostname: "web-portal.javierum.com"
  tlsSecret: "web-portal-prod-tls"
  certManager:
    enabled: true
    clusterIssuer: "letsencrypt-prod"

environment: "production"
