replicaCount: 1

image:
  repository: "javierumunir/portal-tfe"
  tag: "931aa46829fef31e6560585ab2d7c786df781aa6"

service:
  type: ClusterIP
  port: 80

ingress:
  className: nginx
  hostname: "web-portal.javierum.com"
  tlsSecret: "web-portal-prod-tls"
  certManager:
    enabled: true
    clusterIssuer: "letsencrypt-prod"

environment: "production"
