apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-portal
  labels:
    app: web-portal
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-portal
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: web-portal
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: web-portal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ENVIRONMENT
              value: "{{ .Values.environment }}"